#!/usr/bin/env python3

from argparse import ArgumentParser
ARGPARSER=ArgumentParser()
ARGPARSER.add_argument('package_path',required=True,help='Path to the APG package to check')
ARGS=ARGPARSER.parse_args()
from tarfile import open as taropen

class ProceedCheck:
    def __init__(self):
        